{{- if .Values.rbac.clusterRole.create -}}
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ include "api-service.clusterRoleName" . }}
  labels:
    {{- include "api-service.labels" . | nindent 4 }}
  {{- with .Values.rbac.clusterRole.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
rules:
{{- with .Values.rbac.clusterRole.rules }}
  {{- toYaml . | nindent 2 }}
{{- else }}
  []
{{- end }}
{{- end }}
