{{- if .Values.rbac.role.create -}}
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: {{ include "api-service.roleName" . }}
  labels:
    {{- include "api-service.labels" . | nindent 4 }}
  namespace: {{ .Values.rbac.role.namespace | default .Release.Namespace }}
  {{- with .Values.rbac.role.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
rules:
{{- with .Values.rbac.role.rules }}
  {{- toYaml . | nindent 2 }}
{{- else }}
  []
{{- end }}
{{- end }}
