{{- if .Values.secrets.create }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "api-service.secretName" . }}
  labels:
    {{- include "api-service.labels" . | nindent 4 }}
type: Opaque
data:
{{- range $key, $value := .Values.secrets.data }}
  {{ $key }}: {{ include "api-service.getSecretValue" (dict "fieldName" $key "fieldValue" $value "context" $) }}
{{- end }}
{{- end }}